config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :parsed_urls do
    get "parsed_urls/download"
  end
  resources :settings
  resources :websites do
    collection do
      post :parse_websites
    end
  end
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "sessions"}
  resources :roles
  resources :users, only: [:index, :edit, :new, :create, :update, :destroy]
  root 'websites#index'

end

app/models/website.rb
require 'google/api_client'
require 'google/api_client/auth/file_storage'
require 'google/api_client/auth/installed_app'

API_VERSION = 'v2'
CACHED_API_FILE = ".google-fusiontables-#{API_VERSION}.cache"
CREDENTIAL_STORE_FILE = Rails.root.join('tmp', 'google_api_credentials.json')
CLIENT_SECRETS_FILE = Rails.root.join('tmp', 'client_secrets.json')

class Website < ActiveRecord::Base
  has_many :website_urls, :inverse_of => :website, :dependent => :destroy
  accepts_nested_attributes_for :website_urls, :allow_destroy => true
  validates :name, presence: true

  attr_accessor :parsed_websites, :attachments, :exception_errors, :backtrace_errors
  cattr_accessor :client, :drive

  has_many :visits, :inverse_of => :website, :dependent => :destroy
  accepts_nested_attributes_for :visits, :allow_destroy => true

  has_many :parsed_urls

  def self.set_google_drive_connection
    @@client = Google::APIClient.new(:application_name => 'fusion-tables-final',:application_version => '0.1.0')
    Website.create_credential_store_file
    Website.create_client_secrets_file
    file_storage = Google::APIClient::FileStorage.new(CREDENTIAL_STORE_FILE)
    if file_storage.authorization.nil?
      client_secrets = Google::APIClient::ClientSecrets.load(CLIENT_SECRETS_FILE)
      flow = Google::APIClient::InstalledAppFlow.new(
        :client_id => client_secrets.client_id,
        :client_secret => client_secrets.client_secret,
        :scope => ['https://www.googleapis.com/auth/drive']
      )
      @@client.authorization = flow.authorize(file_storage)
      Website.set_credential_record
    else
      @@client.authorization = file_storage.authorization
    end
    @@drive = @@client.discovered_api('drive', API_VERSION)
  end

  def self.create_client_secrets_file
    client_secrets_record = Setting.where(key: "client_secrets").first
    client_secrets_file = File.new(CLIENT_SECRETS_FILE, "w+")
    client_secrets_file.puts(client_secrets_record.value)
    client_secrets_file.close
  end

  def self.create_credential_store_file
    file_storage_record = Setting.where(key: "credential_store_file")
    if file_storage_record.present?
      credential_store_file = File.new(CREDENTIAL_STORE_FILE, "w+")
      credential_store_file.puts(file_storage_record.first.value)
      credential_store_file.close
    end
  end

  def self.set_credential_record
    credential_store_record = Setting.where(key: "credential_store_file").first_or_initialize
    credential_store_record.value = IO.read(CREDENTIAL_STORE_FILE)
    credential_store_record.save
  end

  def self.upload_files_to_google_drive(source_file_path, upload_file_title)
    result = @@client.execute(
      api_method: @@drive.files.list,
      parameters: {
        q: %(title = "#{upload_file_title}")
      }
    )
    existing_file = result.data['items'].first
    mime_type = 'application/octet-stream'
    media = Google::APIClient::UploadIO.new(source_file_path, mime_type)
    if existing_file.present?
      file = @@drive.files.update.request_schema.new({
        'title' => upload_file_title,
        'description' => upload_file_title,
        'mimeType' => mime_type
      })
      file.parents = [{"id" => '0BzVF4wnhYHPXQk9ibjBoN0RrSzg'}]
      result = @@client.execute(
        :api_method => @@drive.files.update,
        :body_object => file,
        :media => media,
        :parameters => {
          'uploadType' => 'multipart',
          'fileId' => existing_file.id,
          'alt' => 'json'
        }
      )
    else
      file = @@drive.files.insert.request_schema.new({
        'title' => upload_file_title,
        'description' => upload_file_title,
        'mimeType' => mime_type
      })
      file.parents = [{"id" => '0BzVF4wnhYHPXQk9ibjBoN0RrSzg'}]
      result = @@client.execute(
        :api_method => @@drive.files.insert,
        :body_object => file,
        :media => media,
        :parameters => {
          'uploadType' => 'multipart',
          'alt' => 'json'
        }
      )
    end
  end

  def self.download_files_from_google_drive(download_file_title, path, source_file)
    result = @@client.execute(
      api_method: @@drive.files.list,
      parameters: {
        q: %(title = "#{download_file_title}")
      }
    )
    file = result.data['items'].first
    if file.present?
      download_url = file['downloadUrl']
      result = @@client.execute(uri: download_url)
      IO.binwrite source_file, result.body
      Website.unzip(source_file, path, true)
    end
  end

  def report_mail_ids
    Setting.where(key: "report_mail_id").map(&:value)
  end

  def reports(websites)
    if websites.present?
      Report.where(website_name: websites.map(&:name))
    else
      Report.all
    end
  end

  def self.parse_wfis_website_by_website
    Website.all.each do |website|
      Website.parse_wfis(website.id)
    end
  end

  def self.clean_folder
    FileUtils.rm_rf("#{Rails.root}/tmp/#{(Date.today-1).strftime('%Y')}")
  end

  def self.parse_wfis(website_id = [])
    websites = []
    begin
    Website.set_google_drive_connection
    bucket = nil
    # websites = website_id.present? ? Website.find(website_id) : Website.all
    websites = website_id.present? ? Website.find([website_id].flatten) : Website.all
    notifications = {}
    attachments = []
    Website.clean_folder
    websites.each do |website|
      Website.download_from_s3_and_unzip(website, bucket)
      file_name = ""
      website_name = website.name
      website.website_urls.each do |website_url|
        respective_parameter_groups = RespectiveParameterGroup.includes(:website_url).where('website_url_id = ?', website_url.id)
        respective_parameters = RespectiveParameter.includes(:respective_parameter_group).where('respective_parameter_group_id IN (?)', respective_parameter_groups.map(&:id))
        url = Website.replace_common_parameter_values(website_url, website_url.url)
        agent = Website.visit_task(website_url, respective_parameters)
        respective_parameter_groups = RespectiveParameterGroup.includes(:website_url).where('website_url_id = ?', website_url.id)
        if respective_parameter_groups.present?
          respective_parameter_groups.each do |respective_parameter_group|
            respective_parameters = RespectiveParameter.includes(:respective_parameter_group).where('respective_parameter_group_id = ?', respective_parameter_group.id)
            file_name = Website.add_file_names(website_url, respective_parameters, website_url.webpage_element.file_name)
            file_name = Website.return_file_path(file_name, website_url.webpage_element, respective_parameters, website)
            book = Website.return_workbook(file_name)
            respective_url = Website.replace_respective_parameter_values(url, respective_parameters)
            Website.xls_generation(website_url, respective_parameters, respective_url, file_name, book, agent, nil, website)
          end
        else
          webpage_element = website_url.webpage_element
          file_name = Website.return_file_name(webpage_element)
          file_name = Website.return_file_path(file_name, webpage_element, respective_parameters, website)
          book = Website.return_workbook(file_name)
          Website.xls_generation(website_url, nil, url, file_name, book, agent, webpage_element.group_by_element, website)
        end
      end
      Website.zip_and_upload_on_s3(website, bucket)
      ###  hard coded
      bucket_url = "https://s3.amazonaws.com/wfisystem/"
      download_url_path = file_name.gsub("#{Rails.root}/tmp/", "")
      if download_url_path.index("xlsx")
        xlsx_file = download_url_path.split("/")[-1]
        download_url_path = download_url_path.gsub("/#{xlsx_file}", "") + ".zip"
        download_url_path = bucket_url + download_url_path
      end
      notifications.merge!({ website.name => download_url_path })
      attachments << Website.return_folder_path(website) + ".zip"
    end
    @website = Website.new
    @website.attachments = attachments
    notifications.each do |website_name, url|
      website = Website.where(name: website_name).first
      parsed_url = ParsedUrl.find_or_initialize_by(url: url)
      parsed_url.date = Date.today - 1
      parsed_url.website_id = website.id
      parsed_url.save
      @website.parsed_websites ||= []
      @website.parsed_websites << website_name
    end
    WebsiteMailer.send_notification(@website, websites).deliver
    attachments.each do |attachment|
      FileUtils.rm(attachment)
    end
      # end
    rescue Exception => e
      @website = Website.new
      # @website.exception_errors = e.message
      @website.parsed_websites = websites.map(&:name)
      @website.exception_errors = e.message
      @website.backtrace_errors = e.backtrace
      WebsiteMailer.send_errors(@website).deliver
    end
  end

  def self.s3_configuration
    require 'aws-sdk'
    bucket_name = 'wfisystem'
    AWS.config(
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    )
    s3 = AWS::S3.new
    bucket = s3.buckets[bucket_name]
    unless bucket.exists?
      bucket = s3.buckets.create(bucket_name)
    end
    return bucket
  end

  def self.zip_and_upload_on_s3(website, bucket)
    source_file_path = Website.zip_file(website)
    key = source_file_path.split("tmp/").last
    upload_file_title = Website.drive_file_name(key)
    Website.upload_files_to_google_drive(source_file_path, upload_file_title)
  end

  def self.drive_file_name(name)
    name.gsub('/', '_')
  end

  def self.zip_file(website)
    path = Website.return_folder_path(website)
    source_file_path = path + ".zip"
    Website.zip(path, source_file_path, true)
    return source_file_path
  end

  def self.download_from_s3_and_unzip(website, bucket)
    path = Website.return_folder_path(website)
    source_file = path + ".zip"
    key = source_file.split("tmp/").last
    folder_path = path.split("/")[0..-2].join("/")

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @websites = Website.all
    respond_with(@websites)
  end

  def show
    respond_with(@website)
  end

  def new
    @website = Website.new
    build_objects
    respond_with(@website)
  end

  def edit
  end

  def create
    @website = Website.new(website_params)
    @website.save
    respond_with(@website)
  end

  def update
    @website.update(website_params)
    respond_with(@website)
  end

  def destroy
    @website.destroy
    respond_with(@website)
  end

  def parse_websites
    if params[:websites].present?
      Website.delay.parse_wfis(params[:websites].map(&:to_i).compact)
      redirect_to websites_url, :notice => "Parsed data successfully"
    end
  end

  private
    def set_website
      @website = Website.find(params[:id])
    end

    def build_objects
      website_url = @website.website_urls.build
      visit = @website.visits.build
      visit.visit_parameters.build
      visit.respective_visits.build
      website_url.common_parameters.build
      website_url.respective_parameter_groups.build.respective_parameters.build
      website_url.build_webpage_element
    end

    def website_params
      params.require(:website).permit(
        :name,
        :folder_path,
        :_destroy,
        visits_attributes: [
          :id,
          :_destroy,
          :url,
          visit_parameters_attributes: [
            :id,
            :_destroy,
            :content_path,
            :data_path,
            :symbol,
            :data_type,
            :ignore_value,
            :visit_parameter_url
          ],
          respective_visits_attributes: [
            :id,
            :_destroy,
            :visit_id,
            :content_path,
            :data_path,
            :symbol,
            :data_type,
            :ignore_value
          ]
        ],
        website_urls_attributes: [
          :id,
          :_destroy,
          :url,
          common_parameters_attributes: [
            :id,
            :_destroy,
            :website_url_id,
            :symbol,
            :value
          ],
          webpage_element_attributes: [
            :id,
            :_destroy,
            :website_url_id,
            :heading_path,
            :content_path,
            :content_loop_path,
            :data_path,
            :header_path,
            :folder_path,
            :file_name,
            :sheet_name,
            :group_by_element
          ],
          respective_parameter_groups_attributes: [
            :id,
            :_destroy,
            :website_url_id,
            respective_parameters_attributes: [
              :id,
              :_destroy,
              :website_url_id,
              :symbol,
              :value
            ]
          ]
        ]
      )
    end
end

app/views/websites/_common_parameter_fields.html.haml
.fields.container
  .form-group.row
    = f.label :symbol
    = f.text_field :symbol, :autofocus => true
    = f.label :value
    = f.text_field :value, :autofocus => true
    = link_to_remove_fields "remove", f

app/views/websites/_form.html.haml
.panel.panel-default
  .panel-heading
    .panel-title
      .row
        .col-md-4
          Add website details
        .col-md-8
          .pull-right
            = link_to "Back", "/websites", class: "btn btn-info active"
  .panel-body
    = form_for(@website, :html => { :role => "form" }) do |f|
      = render 'shared/error_messages', { object: @website }
      .form-group
        = f.label :name, "Website Name"
        = f.text_field :name, :autofocus => true
      .form-group
        = f.label :folder_path, "Folder Path"
        = f.text_field :folder_path, :autofocus => true
      = f.fields_for :visits do |builder|
        = render "visit_fields", :f => builder
      = link_to_add_fields "Add a Visit", f, :visits, "btn btn-primary", "Add a new Visit"
      = f.fields_for :website_urls do |builder|
        = render "website_url_fields", :f => builder
      = link_to_add_fields "Add a Website Url", f, :website_urls, "btn btn-primary", "Add a new Website Url"
      .actions.text-center
        = f.submit "Submit", :class => "btn btn-success"

app/views/websites/_parameter_fields.html.haml
.fields.container
  .form-group.row
    = f.label :symbol
    = f.text_field :symbol, :autofocus => true
    = f.label :value
    = f.text_field :value, :autofocus => true
    = link_to_remove_fields "remove", f

app/views/websites/_respective_parameter_fields.html.haml
.fields.container
  .form-group.row
    = f.label :symbol
    = f.text_field :symbol, :autofocus => true
    = f.label :value
    = f.text_field :value, :autofocus => true
    = link_to_remove_fields "remove", f

app/views/websites/_respective_parameter_group_fields.html.haml
.fields.container.add-border
  .form-group.row
    = f.fields_for :respective_parameters do |builder|
      = render 'respective_parameter_fields', :f => builder
    = link_to_add_fields "Add a respective parameter", f, :respective_parameters, "btn btn-default", "Add a new respective parameter"
    = link_to_remove_fields "remove", f

app/views/websites/_respective_visit_fields.html.haml
.fields.container.add-border
  .form-group.row
    = f.label :content_path
    = f.text_field :content_path, :autofocus => true
    = f.label :data_path
    = f.text_field :data_path, :autofocus => true
    = f.label :symbol
    = f.text_field :symbol, :autofocus => true
    = f.label :data_type
    = f.text_field :data_type, :autofocus => true
    = f.label :ignore_value
    = f.text_field :ignore_value, :autofocus => true
    = link_to_remove_fields "remove", f

app/views/websites/_visit_fields.html.haml
.fields.container.add-border
  .form-group.row
    = f.label :url, "Visit url"
    = f.text_field :url, :autofocus => true
    = link_to_remove_fields "remove", f
  = f.fields_for :visit_parameters do |builder|
    = render 'visit_parameter_fields', :f => builder
  = link_to_add_fields "Add a visit parameter", f, :visit_parameters, "btn btn-default", "Add a new visit parameter"
  = f.fields_for :respective_visits do |builder|
    = render 'respective_visit_fields', :f => builder
  = link_to_add_fields "Add a respective visit", f, :respective_visits, "btn btn-default", "Add a new respective visit"

app/views/websites/_visit_parameter_fields.html.haml
.fields.container.add-border
  .form-group.row
    = f.label :content_path
    = f.text_field :content_path, :autofocus => true
    = f.label :data_path
    = f.text_field :data_path, :autofocus => true
    = f.label :symbol
    = f.text_field :symbol, :autofocus => true
    = f.label :data_type
    = f.text_field :data_type, :autofocus => true
    = f.label :ignore_value
    = f.text_field :ignore_value, :autofocus => true
    = link_to_remove_fields "remove", f

app/views/websites/_webpage_element_fields.html.haml
.fields.container.add-border
  .form-group.row
    = f.label :heading_path
    = f.text_field :heading_path, autofocus: true
    = f.label :content_path
    = f.text_field :content_path, autofocus: true
    = f.label :content_loop_path
    = f.text_field :content_loop_path, autofocus: true
    = f.label :data_path
    = f.text_field :data_path, autofocus: true
    %br
    = f.label :header_path
    = f.text_field :header_path, autofocus: true
    = f.label :folder_path
    = f.text_field :folder_path, autofocus: true
    = f.label :file_name
    = f.text_field :file_name, autofocus: true
    = f.label :sheet_name
    = f.text_field :sheet_name, autofocus: true
    = f.label :group_by_element
    = f.text_field :group_by_element, autofocus: true
    =# link_to_remove_fields "remove", f

app/views/websites/_webpage_elements_website_url_fields.html.haml
.fields.container.add-border
  .form-group.row
    = f.label :file_name
    = f.text_field :file_name, :autofocus => true
    = link_to_remove_fields "remove", f

  = f.fields_for :webpage_element do |builder|
    = render 'webpage_element_fields', :f => builder
  = link_to_add_fields "Add webpage element", f, :webpage_element, "btn btn-default", "Add a new webpage element"

app/views/websites/_website_url_fields.html.haml
.fields.container.add-border
  .form-group.row
    = f.label :url, "Website Url"
    = f.text_field :url, :autofocus => true
    = link_to_remove_fields "remove", f
  = f.fields_for :common_parameters do |builder|
    = render 'common_parameter_fields', :f => builder
  = link_to_add_fields "Add a common parameter", f, :common_parameters, "btn btn-default", "Add a new common parameter"
  = f.fields_for :respective_parameter_groups do |builder|
    = render 'respective_parameter_group_fields', :f => builder
  = link_to_add_fields "Add a respective parameter group", f, :respective_parameter_groups, "btn btn-default", "Add a new respective parameter group"

  = f.fields_for :webpage_element do |builder|
    = render 'webpage_element_fields', :f => builder
  = link_to_add_fields "Add webpage elements", f, :webpage_element, "btn btn-default", "Add a new webpage element"

app/views/websites/edit.html.erb
<%= render 'form' %>

app/views/websites/index.html.haml
%h1 Parse websites
%br
= form_tag parse_websites_websites_path do
  = label_tag "Websites"
  %br
  =select_tag 'websites[]', options_for_select(@websites.map {|w| [w.name, w.id]}), :multiple => true, :size => 10, :style => "width:200px"
  %br
  = submit_tag "Submit", class: "btn btn-large btn-primary"

%h1 Listing websites

%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @websites.each do |website|
      %tr
        %td= website.name
        %td= link_to 'Show', website
        %td= link_to 'Edit', edit_website_path(website)
        %td= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Website', new_website_path

app/views/websites/new.html.erb
<%= render 'form' %>