config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :parsed_urls do
    get "parsed_urls/download"
  end
  resources :settings
  resources :websites do
    collection do
      post :parse_websites
    end
  end
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "sessions"}
  resources :roles
  resources :users, only: [:index, :edit, :new, :create, :update, :destroy]
  root 'websites#index'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @settings = Setting.all
    respond_with(@settings)
  end

  def show
    respond_with(@setting)
  end

  def new
    @setting = Setting.new
    respond_with(@setting)
  end

  def edit
  end

  def create
    @setting = Setting.new(setting_params)
    @setting.save
    respond_with(@setting)
  end

  def update
    @setting.update(setting_params)
    respond_with(@setting)
  end

  def destroy
    @setting.destroy
    respond_with(@setting)
  end

  private
    def set_setting
      @setting = Setting.find(params[:id])
    end

    def setting_params
      params.require(:setting).permit(:key, :value)
    end
end

app/views/settings/_form.html.haml
= form_for(@setting) do |f|
  - if @setting.errors.any?
    #error_explanation
      %h2
        = pluralize(@setting.errors.count, "error")
        prohibited this setting from being saved:
      %ul
        - @setting.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :key
    %br/
    = f.text_field :key
  .field
    = f.label :value
    %br/
    = f.text_field :value
  .actions
    = f.submit

app/views/settings/edit.html.haml
%h1 Editing setting
= render 'form'
= link_to 'Show', @setting
|
= link_to 'Back', settings_path

app/views/settings/index.html.haml
%h1 Listing settings
%table
  %thead
    %tr
      %th Key
      %th Value
      %th{:colspan => "3"}
  %tbody
    - @settings.each do |setting|
      %tr
        %td= setting.key
        %td= setting.value
        %td= link_to 'Show', setting
        %td= link_to 'Edit', edit_setting_path(setting)
        %td= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Setting', new_setting_path

app/views/settings/new.html.haml
%h1 New setting
= render 'form'
= link_to 'Back', settings_path

app/views/settings/show.html.haml
%p#notice= notice
%p
  %strong Key:
  = @setting.key
%p
  %strong Value:
  = @setting.value
= link_to 'Edit', edit_setting_path(@setting)
|
= link_to 'Back', settings_path