config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :parsed_urls do
    get "parsed_urls/download"
  end
  resources :settings
  resources :websites do
    collection do
      post :parse_websites
    end
  end
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "sessions"}
  resources :roles
  resources :users, only: [:index, :edit, :new, :create, :update, :destroy]
  root 'websites#index'

end

app/models/parsed_url.rb
class ParsedUrl < ActiveRecord::Base

  belongs_to :website

end

app/controllers/parsed_urls_controller.rb
class ParsedUrlsController < ApplicationController
  before_action :set_parsed_url, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @parsed_urls = ParsedUrl.all
    respond_with(@parsed_urls)
  end

  def show
    respond_with(@parsed_url)
  end

  def new
    @parsed_url = ParsedUrl.new
    respond_with(@parsed_url)
  end

  def edit
  end

  def create
    @parsed_url = ParsedUrl.new(parsed_url_params)
    @parsed_url.save
    respond_with(@parsed_url)
  end

  def update
    @parsed_url.update(parsed_url_params)
    respond_with(@parsed_url)
  end

  def destroy
    @parsed_url.destroy
    respond_with(@parsed_url)
  end


  def download
    website = ParsedUrl.find(params[:parsed_url_id]).website
    bucket = Website.s3_configuration
    path = Website.return_folder_path(website)
    source_file = path + ".zip"
    key = source_file.split("tmp/").last
    object = bucket.objects[key]
    destination_file = source_file.split("/").last
    destination_file = "#{Rails.root}/tmp/#{destination_file}"
    if object.exists?
      File.open(destination_file, 'wb') do |file|
        object.read do |chunk|
          file.write(chunk)
        end
      end
    end
    send_file destination_file, :type=>"application/zip"
  end

  private
    def set_parsed_url
      @parsed_url = ParsedUrl.find(params[:id])
    end

    def parsed_url_params
      params.require(:parsed_url).permit(:date, :website_id, :string, :url)
    end
end

app/views/parsed_urls/_form.html.erb
<%= form_for(@parsed_url) do |f| %>
  <% if @parsed_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parsed_url.errors.count, "error") %> prohibited this parsed_url from being saved:</h2>

      <ul>
      <% @parsed_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :website_id %><br>
    <%= f.text_field :website_id %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parsed_urls/edit.html.erb
<h1>Editing parsed_url</h1>

<%= render 'form' %>

<%= link_to 'Show', @parsed_url %> |
<%= link_to 'Back', parsed_urls_path %>

app/views/parsed_urls/index.html.erb
<h1>Listing parsed_urls</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Website name</th>
      <th>Url</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @parsed_urls.each do |parsed_url| %>
      <tr>
        <td><%= parsed_url.date %></td>
        <td><%= parsed_url.website.name %></td>
        <td><%= parsed_url.url %></td>
        <td><%= link_to 'Show', parsed_url %></td>
        <td><%= link_to 'Edit', edit_parsed_url_path(parsed_url) %></td>
        <td><%= link_to 'Destroy', parsed_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Download', parsed_url_parsed_urls_download_path(parsed_url.id) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parsed url', new_parsed_url_path %>

app/views/parsed_urls/new.html.erb
<h1>New parsed_url</h1>

<%= render 'form' %>

<%= link_to 'Back', parsed_urls_path %>

app/views/parsed_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @parsed_url.date %>
</p>

<p>
  <strong>Website name:</strong>
  <%= @parsed_url.website_id %>
</p>

<p>
  <strong>String:</strong>
  <%= @parsed_url.string %>
</p>

<p>
  <strong>Url:</strong>
  <%= @parsed_url.url %>
</p>

<%= link_to 'Edit', edit_parsed_url_path(@parsed_url) %> |
<%= link_to 'Back', parsed_urls_path %>