config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :parsed_urls do
    get "parsed_urls/download"
  end
  resources :settings
  resources :websites do
    collection do
      post :parse_websites
    end
  end
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "sessions"}
  resources :roles
  resources :users, only: [:index, :edit, :new, :create, :update, :destroy]
  root 'websites#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @reports = Report.all
    respond_with(@reports)
  end

  def show
    respond_with(@report)
  end

  def new
    @report = Report.new
    respond_with(@report)
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    @report.save
    respond_with(@report)
  end

  def update
    @report.update(report_params)
    respond_with(@report)
  end

  def destroy
    @report.destroy
    respond_with(@report)
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:url, :yesterday_date, :today_date, :yesterday_row_count, :today_row_count, :row_count_difference, :yesterday_column_count, :today_column_count, :column_count_difference)
    end
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :yesterday_date %><br>
    <%= f.date_select :yesterday_date %>
  </div>
  <div class="field">
    <%= f.label :today_date %><br>
    <%= f.date_select :today_date %>
  </div>
  <div class="field">
    <%= f.label :yesterday_row_count %><br>
    <%= f.number_field :yesterday_row_count %>
  </div>
  <div class="field">
    <%= f.label :today_row_count %><br>
    <%= f.number_field :today_row_count %>
  </div>
  <div class="field">
    <%= f.label :row_count_difference %><br>
    <%= f.number_field :row_count_difference %>
  </div>
  <div class="field">
    <%= f.label :yesterday_column_count %><br>
    <%= f.number_field :yesterday_column_count %>
  </div>
  <div class="field">
    <%= f.label :today_column_count %><br>
    <%= f.number_field :today_column_count %>
  </div>
  <div class="field">
    <%= f.label :column_count_difference %><br>
    <%= f.number_field :column_count_difference %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>File Name</th>
      <th>Yesterday date</th>
      <th>Today date</th>
      <th>Yesterday row count</th>
      <th>Today row count</th>
      <th>Row count difference</th>
      <th>Yesterday column count</th>
      <th>Today column count</th>
      <th>Column count difference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.file_name %></td>
        <td><%= report.yesterday_date %></td>
        <td><%= report.today_date %></td>
        <td><%= report.yesterday_row_count %></td>
        <td><%= report.today_row_count %></td>
        <% if report.row_count_difference < 0 %>
          <td style="color: red;"><%= report.row_count_difference %></td>
        <% else %>
          <td><%= report.row_count_difference %></td>
        <% end %>
        <td><%= report.yesterday_column_count %></td>
        <td><%= report.today_column_count %></td>
        <% if report.column_count_difference < 0 %>
          <td style="color: red;"><%= report.column_count_difference %></td>
        <% else %>
          <td><%= report.column_count_difference %></td>
        <% end %>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File Name:</strong>
  <%= @report.file_name %>
</p>

<p>
  <strong>Yesterday date:</strong>
  <%= @report.yesterday_date %>
</p>

<p>
  <strong>Today date:</strong>
  <%= @report.today_date %>
</p>

<p>
  <strong>Yesterday row count:</strong>
  <%= @report.yesterday_row_count %>
</p>

<p>
  <strong>Today row count:</strong>
  <%= @report.today_row_count %>
</p>

<p>
  <strong>Row Count Difference:</strong>
  <%= @report.row_count_difference %>
</p>

<p>
  <strong>Yesterday column count:</strong>
  <%= @report.yesterday_column_count %>
</p>

<p>
  <strong>Today column count:</strong>
  <%= @report.today_column_count %>
</p>

<p>
  <strong>Column Count Difference:</strong>
  <%= @report.column_count_difference %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>